//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace xubot.src.BotSettings {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Global : ApplicationSettingsBase {
        
        private static Global defaultInstance = ((Global)(Synchronized(new Global())));
        
        public static Global Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DMsAlwaysNSFW {
            get {
                return ((bool)(this["DMsAlwaysNSFW"]));
            }
            set {
                this["DMsAlwaysNSFW"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int EmbedListMaxLength {
            get {
                return ((int)(this["EmbedListMaxLength"]));
            }
            set {
                this["EmbedListMaxLength"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DisableRedditOnStart {
            get {
                return ((bool)(this["DisableRedditOnStart"]));
            }
            set {
                this["DisableRedditOnStart"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("./Exceptions/")]
        public string ExceptionLogLocation {
            get {
                return ((string)(this["ExceptionLogLocation"]));
            }
            set {
                this["ExceptionLogLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SendStacktraceOnError {
            get {
                return ((bool)(this["SendStacktraceOnError"]));
            }
            set {
                this["SendStacktraceOnError"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SendBigStacktraceOnError {
            get {
                return ((bool)(this["SendBigStacktraceOnError"]));
            }
            set {
                this["SendBigStacktraceOnError"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool BotwideNSFWEnabled {
            get {
                return ((bool)(this["BotwideNSFWEnabled"]));
            }
            set {
                this["BotwideNSFWEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("💭")]
        public string WorkingReaction {
            get {
                return ((string)(this["WorkingReaction"]));
            }
            set {
                this["WorkingReaction"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("✅")]
        public string WorkCompletedReaction {
            get {
                return ((string)(this["WorkCompletedReaction"]));
            }
            set {
                this["WorkCompletedReaction"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("🕒")]
        public string WorkTakingLongerReaction {
            get {
                return ((string)(this["WorkTakingLongerReaction"]));
            }
            set {
                this["WorkTakingLongerReaction"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5000")]
        public int TakingLongerMilliseconds {
            get {
                return ((int)(this["TakingLongerMilliseconds"]));
            }
            set {
                this["TakingLongerMilliseconds"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("50")]
        public int TaskPollLength {
            get {
                return ((int)(this["TaskPollLength"]));
            }
            set {
                this["TaskPollLength"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("notinteresting")]
        public string StartingSubreddit {
            get {
                return ((string)(this["StartingSubreddit"]));
            }
            set {
                this["StartingSubreddit"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string StartingRedditQuery {
            get {
                return ((string)(this["StartingRedditQuery"]));
            }
            set {
                this["StartingRedditQuery"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int StartingRedditSorting {
            get {
                return ((int)(this["StartingRedditSorting"]));
            }
            set {
                this["StartingRedditSorting"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool StartingRedditHideOutput {
            get {
                return ((bool)(this["StartingRedditHideOutput"]));
            }
            set {
                this["StartingRedditHideOutput"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SuperSimpleTypes {
            get {
                return ((bool)(this["SuperSimpleTypes"]));
            }
            set {
                this["SuperSimpleTypes"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("xub>")]
        public string HardcodedPrefix {
            get {
                return ((string)(this["HardcodedPrefix"]));
            }
            set {
                this["HardcodedPrefix"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("[>")]
        public string DefaultPrefix {
            get {
                return ((string)(this["DefaultPrefix"]));
            }
            set {
                this["DefaultPrefix"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("d>")]
        public string DefaultDevPrefix {
            get {
                return ((string)(this["DefaultDevPrefix"]));
            }
            set {
                this["DefaultDevPrefix"] = value;
            }
        }
    }
}
